name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Extract version
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build macOS binary
        run: |
          mkdir -p build

          OUTPUT="stackforge-${{ steps.vars.outputs.VERSION }}-darwin-${{ matrix.goarch }}"

          GOOS=darwin \
          GOARCH=${{ matrix.goarch }} \
          go build -o build/$OUTPUT ./cmd

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: stackforge-${{ matrix.goarch }}
          path: build/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
